### ISSUE TITLE
[Improvement] Temp file folder should be a subdirectory of output directory, not system temp

### ISSUE THREAD

**Issue by pierotofy** [HeDo88TH/Obj2Tiles#6]
As title says.

**Comment by HeDo88TH** [comment]
it will use a subdirectory of the output directory and I will add a `--use-system-temp` command line switch to make it use the system temp

**Comment by pierotofy** [comment]
Then it should get cleaned up at pipeline completion. :+1:

**Comment by HeDo88TH** [comment]
Added!
